# Use the official Node.js 14 image as the base image
FROM node:18 AS build

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application's code to the working directory
COPY . .

# Build the Next.js app
RUN npm run build

# Use a smaller, lightweight image as the base for production
FROM node:18-alpine

# Set the working directory inside the container
# WORKDIR /app

# Copy the server.js file to the working directory
COPY server.js .

# Copy the built Next.js app from the previous stage
COPY --from=build /app/.next ./.next
COPY --from=build /app/messages ./messages

COPY --from=build /app/public ./public
COPY --from=build /app/package*.json ./
COPY --from=build /app/localization*.ts ./
COPY --from=build /app/middleware*.ts ./
COPY --from=build /app/next.config*.js ./
COPY --from=build /app/next-env.d*.ts ./

# Install production dependencies
RUN npm install

# Expose the port that the Next.js app will run on
EXPOSE 3000

# Start the Next.js app
CMD [ "node", "server.js" ]